from sqlalchemy import Column,Integer,BigInteger,String,Text,Float,Boolean,Date,DateTime,ForeignKey,UniqueConstraint
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.database.db_connection import Base
class User(Base):
    __tablename__='users'
    id=Column(Integer,primary_key=True,index=True)
    name=Column(String(150),nullable=False)
    email=Column(String(255),unique=True,index=True,nullable=False)
    password_hash=Column(Text,nullable=False)
    role=Column(String(50),default='user')
    is_active=Column(Boolean,default=True)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
class Tender(Base):
    __tablename__='tenders'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    source=Column(String(100),nullable=False)
    tender_id=Column(String(255),nullable=False)
    title=Column(Text,nullable=False)
    department=Column(Text); state=Column(String(100)); estimated_value=Column(BigInteger); deadline=Column(Date); url=Column(Text); description=Column(Text); category=Column(String(255))
    relevance_score=Column(Float); ai_recommendation=Column(Boolean); ai_reason=Column(Text)
    status=Column(String(100),default='new')
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
    tracking=relationship('TenderTracking',back_populates='tender',uselist=False)
    eligibility=relationship('TenderEligibility',uselist=False)
    bid_decision=relationship('BidDecision',uselist=False)
    __table_args__=(UniqueConstraint('user_id','source','tender_id',name='uq_user_source_tender_id'),)
class TenderTracking(Base):
    __tablename__='tender_tracking'
    id=Column(Integer,primary_key=True,index=True)
    tender_id=Column(Integer,ForeignKey('tenders.id'),nullable=False)
    submission_status=Column(String(100),default='not_started'); documents_ready=Column(Boolean,default=False); applied=Column(Boolean,default=False); evaluation_status=Column(String(100)); remarks=Column(Text)
    source_status=Column(String(100)); last_checked_at=Column(DateTime(timezone=True)); source_available=Column(Boolean,default=False)
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
    tender=relationship('Tender',back_populates='tracking')
class ScrapingLog(Base):
    __tablename__='scraping_logs'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    source=Column(String(100),nullable=False); status=Column(String(50),nullable=False); message=Column(Text)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
class ScrapeKeyword(Base):
    __tablename__='scrape_keywords'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    keyword=Column(String(255),index=True,nullable=False)
    profile=Column(String(100),default='Custom')
    synonyms=Column(Text)
    is_active=Column(Boolean,default=True)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    __table_args__=(UniqueConstraint('user_id','keyword',name='uq_user_scrape_keyword'),)
class AppSetting(Base):
    __tablename__='app_settings'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    key=Column(String(100),index=True,nullable=False)
    value=Column(String(255),nullable=False)
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
    __table_args__=(UniqueConstraint('user_id','key',name='uq_user_app_setting'),)
class ScoringCriterion(Base):
    __tablename__='scoring_criteria'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    keyword=Column(String(255),index=True,nullable=False)
    weight=Column(Integer,default=10,nullable=False)
    match_type=Column(String(50),default='positive')
    profile=Column(String(100),default='Custom')
    is_active=Column(Boolean,default=True)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    __table_args__=(UniqueConstraint('user_id','keyword',name='uq_user_scoring_keyword'),)
class TelegramSubscriber(Base):
    __tablename__='telegram_subscribers'
    id=Column(Integer,primary_key=True,index=True)
    chat_id=Column(String(100),unique=True,index=True,nullable=False)
    username=Column(String(255))
    first_name=Column(String(255))
    chat_type=Column(String(50))
    is_active=Column(Boolean,default=True)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class NotificationPreference(Base):
    __tablename__='notification_preferences'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True,nullable=False)
    channel=Column(String(50),nullable=False)
    enabled=Column(Boolean,default=True)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
    __table_args__=(UniqueConstraint('user_id','channel',name='uq_user_notification_channel'),)
class NotificationLog(Base):
    __tablename__='notification_logs'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    tender_id=Column(Integer,ForeignKey('tenders.id'),index=True)
    channel=Column(String(50),nullable=False)
    recipient=Column(String(255))
    status=Column(String(50),nullable=False)
    message=Column(Text)
    error=Column(Text)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
class ScrapeRun(Base):
    __tablename__='scrape_runs'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    trigger=Column(String(50),default='manual')
    source=Column(String(100),default='GeM')
    status=Column(String(50),default='running')
    inserted_count=Column(Integer,default=0)
    scored_count=Column(Integer,default=0)
    telegram_count=Column(Integer,default=0)
    email_count=Column(Integer,default=0)
    removed_low_priority_count=Column(Integer,default=0)
    message=Column(Text)
    started_at=Column(DateTime(timezone=True),server_default=func.now())
    finished_at=Column(DateTime(timezone=True))
class ScrapeJob(Base):
    __tablename__='scrape_jobs'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    job_type=Column(String(50),default='scrape')
    status=Column(String(50),default='queued')
    payload=Column(Text)
    result=Column(Text)
    error=Column(Text)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    started_at=Column(DateTime(timezone=True))
    finished_at=Column(DateTime(timezone=True))
class TenderDocument(Base):
    __tablename__='tender_documents'
    id=Column(Integer,primary_key=True,index=True)
    tender_id=Column(Integer,ForeignKey('tenders.id'),index=True,nullable=False)
    document_type=Column(String(50),default='raw_bid')
    url=Column(Text)
    file_path=Column(Text)
    status=Column(String(50),default='pending')
    extracted_text=Column(Text)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class TenderEligibility(Base):
    __tablename__='tender_eligibility'
    id=Column(Integer,primary_key=True,index=True)
    tender_id=Column(Integer,ForeignKey('tenders.id'),unique=True,index=True,nullable=False)
    emd=Column(Text)
    turnover_requirement=Column(Text)
    experience_requirement=Column(Text)
    documents_required=Column(Text)
    certifications_required=Column(Text)
    submission_deadline=Column(Text)
    payment_terms=Column(Text)
    technical_specs=Column(Text)
    risk_flags=Column(Text)
    summary=Column(Text)
    extracted_from=Column(String(100),default='description')
    confidence=Column(Float,default=0)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class BidDecision(Base):
    __tablename__='bid_decisions'
    id=Column(Integer,primary_key=True,index=True)
    tender_id=Column(Integer,ForeignKey('tenders.id'),unique=True,index=True,nullable=False)
    recommendation=Column(String(50),default='review')
    decision_score=Column(Float,default=0)
    reasons=Column(Text)
    blockers=Column(Text)
    next_steps=Column(Text)
    confidence=Column(Float,default=0)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class KeywordPerformance(Base):
    __tablename__='keyword_performance'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),index=True)
    scrape_run_id=Column(Integer,ForeignKey('scrape_runs.id'),index=True)
    keyword=Column(String(255),index=True,nullable=False)
    fetched_count=Column(Integer,default=0)
    inserted_count=Column(Integer,default=0)
    duplicate_count=Column(Integer,default=0)
    high_priority_count=Column(Integer,default=0)
    average_score=Column(Float,default=0)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
class MarketingLead(Base):
    __tablename__='marketing_leads'
    id=Column(Integer,primary_key=True,index=True)
    lead_type=Column(String(50),default='demo',index=True)
    name=Column(String(150))
    email=Column(String(255),index=True,nullable=False)
    company=Column(String(255))
    phone=Column(String(50))
    plan=Column(String(100))
    message=Column(Text)
    source_page=Column(String(255))
    created_at=Column(DateTime(timezone=True),server_default=func.now())
class CompanyProfile(Base):
    __tablename__='company_profiles'
    id=Column(Integer,primary_key=True,index=True)
    user_id=Column(Integer,ForeignKey('users.id'),unique=True,index=True,nullable=False)
    company_name=Column(String(255))
    products=Column(Text)
    services=Column(Text)
    industries=Column(Text)
    target_departments=Column(Text)
    target_states=Column(Text)
    certifications=Column(Text)
    experience_keywords=Column(Text)
    negative_keywords=Column(Text)
    min_tender_value=Column(BigInteger)
    max_tender_value=Column(BigInteger)
    is_active=Column(Boolean,default=True)
    created_at=Column(DateTime(timezone=True),server_default=func.now())
    updated_at=Column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
